# Generated by Django 5.2.10 on 2026-01-28 19:43

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Form introduction text')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Text to display after form submission')),
            ],
            options={
                'verbose_name': 'Contact Form Page',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='PracticePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Wagtail CMS Test Page', help_text='Main hero title', max_length=200)),
                ('hero_subtitle', models.TextField(default='This page is created to test Wagtail Page Models, Fields, and StreamField concepts.', help_text='Hero subtitle/description')),
                ('hero_publish_date', models.DateField(help_text='Display publish date in hero section')),
                ('about_title', models.CharField(default='About This Page', help_text='About section title', max_length=200)),
                ('about_content', wagtail.fields.RichTextField(help_text='Rich text content for about section')),
                ('author', models.CharField(default='Admin User', help_text='Page author name', max_length=100)),
                ('category', models.CharField(default='CMS Practice', help_text='Page category', max_length=100)),
                ('status', models.CharField(default='Published', help_text='Page status', max_length=50)),
                ('last_updated', models.DateField(auto_now=True, help_text='Last update date')),
                ('featured_articles', wagtail.fields.StreamField([('card', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Card image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card title', 'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Card description'}), 3: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date'}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('publish_date', 3)]], {})}, help_text='Add featured article cards')),
                ('form_section_title', models.CharField(default='Contact / Form Testing', help_text='Form section title', max_length=200)),
            ],
            options={
                'verbose_name': 'Practice Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='practice.contactformpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
