# Generated by Django 5.2.10 on 2026-01-28 20:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformpage',
            name='intro_ar',
            field=wagtail.fields.RichTextField(blank=True, help_text='Form introduction text', null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='intro_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Form introduction text', null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='thank_you_text_ar',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display after form submission', null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='thank_you_text_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display after form submission', null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='about_content_ar',
            field=wagtail.fields.RichTextField(help_text='Rich text content for about section', null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='about_content_en',
            field=wagtail.fields.RichTextField(help_text='Rich text content for about section', null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='about_title_ar',
            field=models.CharField(default='About This Page', help_text='About section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='about_title_en',
            field=models.CharField(default='About This Page', help_text='About section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='author_ar',
            field=models.CharField(default='Admin User', help_text='Page author name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='author_en',
            field=models.CharField(default='Admin User', help_text='Page author name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='category_ar',
            field=models.CharField(default='CMS Practice', help_text='Page category', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='category_en',
            field=models.CharField(default='CMS Practice', help_text='Page category', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='form_section_title_ar',
            field=models.CharField(default='Contact / Form Testing', help_text='Form section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='form_section_title_en',
            field=models.CharField(default='Contact / Form Testing', help_text='Form section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='hero_subtitle_ar',
            field=models.TextField(default='This page is created to test Wagtail Page Models, Fields, and StreamField concepts.', help_text='Hero subtitle/description', null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='hero_subtitle_en',
            field=models.TextField(default='This page is created to test Wagtail Page Models, Fields, and StreamField concepts.', help_text='Hero subtitle/description', null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='hero_title_ar',
            field=models.CharField(default='Wagtail CMS Test Page', help_text='Main hero title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='hero_title_en',
            field=models.CharField(default='Wagtail CMS Test Page', help_text='Main hero title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='status_ar',
            field=models.CharField(default='Published', help_text='Page status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='practicepage',
            name='status_en',
            field=models.CharField(default='Published', help_text='Page status', max_length=50, null=True),
        ),
    ]
