# Generated by Django 5.2.10 on 2026-01-29 07:45

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_remove_practicepage_featured_articles_and_more'),
        ('wagtailcore', '0097_page_search_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('hero_title', models.CharField(default='User Registration', help_text='Main title displayed in hero section', max_length=255, verbose_name='Hero Title')),
                ('hero_title_en', models.CharField(default='User Registration', help_text='Main title displayed in hero section', max_length=255, null=True, verbose_name='Hero Title')),
                ('hero_title_ar', models.CharField(default='User Registration', help_text='Main title displayed in hero section', max_length=255, null=True, verbose_name='Hero Title')),
                ('hero_subtitle', models.TextField(blank=True, help_text='Subtitle text in hero section', verbose_name='Hero Subtitle')),
                ('hero_subtitle_en', models.TextField(blank=True, help_text='Subtitle text in hero section', null=True, verbose_name='Hero Subtitle')),
                ('hero_subtitle_ar', models.TextField(blank=True, help_text='Subtitle text in hero section', null=True, verbose_name='Hero Subtitle')),
                ('form_title', models.CharField(default='Create Your Account', help_text='Title above the registration form', max_length=255, verbose_name='Form Title')),
                ('form_title_en', models.CharField(default='Create Your Account', help_text='Title above the registration form', max_length=255, null=True, verbose_name='Form Title')),
                ('form_title_ar', models.CharField(default='Create Your Account', help_text='Title above the registration form', max_length=255, null=True, verbose_name='Form Title')),
                ('form_description', wagtail.fields.RichTextField(blank=True, help_text='Description text above the form', verbose_name='Form Description')),
                ('form_description_en', wagtail.fields.RichTextField(blank=True, help_text='Description text above the form', null=True, verbose_name='Form Description')),
                ('form_description_ar', wagtail.fields.RichTextField(blank=True, help_text='Description text above the form', null=True, verbose_name='Form Description')),
                ('thank_you_title', models.CharField(default='Thank You!', help_text='Title shown on success page', max_length=255, verbose_name='Thank You Title')),
                ('thank_you_title_en', models.CharField(default='Thank You!', help_text='Title shown on success page', max_length=255, null=True, verbose_name='Thank You Title')),
                ('thank_you_title_ar', models.CharField(default='Thank You!', help_text='Title shown on success page', max_length=255, null=True, verbose_name='Thank You Title')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Message shown after successful registration', verbose_name='Thank You Message')),
                ('thank_you_text_en', wagtail.fields.RichTextField(blank=True, help_text='Message shown after successful registration', null=True, verbose_name='Thank You Message')),
                ('thank_you_text_ar', wagtail.fields.RichTextField(blank=True, help_text='Message shown after successful registration', null=True, verbose_name='Thank You Message')),
            ],
            options={
                'verbose_name': 'Registration Page',
                'verbose_name_plural': 'Registration Pages',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='practice.contactformpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='practice.registrationpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
