# Generated by Django 5.2.10 on 2026-01-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_registrationpage_contactformfield_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformpage',
            options={'verbose_name': 'Contact Form Page', 'verbose_name_plural': 'Contact Form Pages'},
        ),
        migrations.AddField(
            model_name='contactformfield',
            name='choices_ar',
            field=models.TextField(blank=True, help_text='Comma or new line separated list of choices in Arabic', verbose_name='Choices (Arabic)'),
        ),
        migrations.AddField(
            model_name='contactformfield',
            name='help_text_ar',
            field=models.TextField(blank=True, help_text='Arabic translation of the help text', verbose_name='Help Text (Arabic)'),
        ),
        migrations.AddField(
            model_name='contactformfield',
            name='label_ar',
            field=models.CharField(blank=True, help_text='Arabic translation of the field label', max_length=255, verbose_name='Label (Arabic)'),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='choices_ar',
            field=models.TextField(blank=True, help_text='Comma or new line separated list of choices in Arabic', verbose_name='Choices (Arabic)'),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='help_text_ar',
            field=models.TextField(blank=True, help_text='Arabic translation of the help text', verbose_name='Help Text (Arabic)'),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='label_ar',
            field=models.CharField(blank=True, help_text='Arabic translation of the field label', max_length=255, verbose_name='Label (Arabic)'),
        ),
    ]
