# Generated by Django 5.2.10 on 2026-01-29 09:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_remove_registrationformfield_page_and_more'),
        ('wagtailcore', '0097_page_search_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='User Registration', help_text='Main heading for registration page', max_length=255)),
                ('hero_title_en', models.CharField(default='User Registration', help_text='Main heading for registration page', max_length=255, null=True)),
                ('hero_title_ar', models.CharField(default='User Registration', help_text='Main heading for registration page', max_length=255, null=True)),
                ('hero_subtitle', models.TextField(default='Create your account to get started', help_text='Subtitle text below main heading')),
                ('hero_subtitle_en', models.TextField(default='Create your account to get started', help_text='Subtitle text below main heading', null=True)),
                ('hero_subtitle_ar', models.TextField(default='Create your account to get started', help_text='Subtitle text below main heading', null=True)),
                ('form_intro_title', models.CharField(default='Register Now', help_text='Title above the form', max_length=255)),
                ('form_intro_title_en', models.CharField(default='Register Now', help_text='Title above the form', max_length=255, null=True)),
                ('form_intro_title_ar', models.CharField(default='Register Now', help_text='Title above the form', max_length=255, null=True)),
                ('form_intro_text', wagtail.fields.RichTextField(blank=True, default='<p>Fill in the details below to create your account.</p>', help_text='Introduction text for the form')),
                ('form_intro_text_en', wagtail.fields.RichTextField(blank=True, default='<p>Fill in the details below to create your account.</p>', help_text='Introduction text for the form', null=True)),
                ('form_intro_text_ar', wagtail.fields.RichTextField(blank=True, default='<p>Fill in the details below to create your account.</p>', help_text='Introduction text for the form', null=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, default="<p>Thank you for registering! We'll get back to you soon.</p>", help_text='Text to display after form submission')),
                ('thank_you_text_en', wagtail.fields.RichTextField(blank=True, default="<p>Thank you for registering! We'll get back to you soon.</p>", help_text='Text to display after form submission', null=True)),
                ('thank_you_text_ar', wagtail.fields.RichTextField(blank=True, default="<p>Thank you for registering! We'll get back to you soon.</p>", help_text='Text to display after form submission', null=True)),
                ('to_address', models.EmailField(blank=True, help_text='Email address to send form submissions to', max_length=254)),
                ('from_address', models.EmailField(blank=True, help_text='Email address to send from', max_length=254)),
                ('subject', models.CharField(blank=True, default='New Registration Submission', help_text='Subject line for email notifications', max_length=255)),
                ('subject_en', models.CharField(blank=True, default='New Registration Submission', help_text='Subject line for email notifications', max_length=255, null=True)),
                ('subject_ar', models.CharField(blank=True, default='New Registration Submission', help_text='Subject line for email notifications', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Registration Page',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.RemoveField(
            model_name='contactformpage',
            name='intro_ar',
        ),
        migrations.RemoveField(
            model_name='contactformpage',
            name='intro_en',
        ),
        migrations.RemoveField(
            model_name='contactformpage',
            name='thank_you_text_ar',
        ),
        migrations.RemoveField(
            model_name='contactformpage',
            name='thank_you_text_en',
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='practice.contactformpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='practice.registrationpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
