# Generated by Django 5.2.10 on 2026-01-29 10:01

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_registrationpage_remove_contactformpage_intro_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationformfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='registrationpage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='intro_ar',
            field=wagtail.fields.RichTextField(blank=True, help_text='Form introduction text', null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='intro_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Form introduction text', null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='thank_you_text_ar',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display after form submission', null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='thank_you_text_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text to display after form submission', null=True),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='practice.contactformpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ContactFormField',
        ),
        migrations.DeleteModel(
            name='RegistrationFormField',
        ),
        migrations.DeleteModel(
            name='RegistrationPage',
        ),
    ]
