# Generated by Django 5.2.10 on 2026-01-29 10:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_remove_registrationformfield_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicepage',
            name='featured_articles',
            field=wagtail.fields.StreamField([('card', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Card image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card title', 'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Card description'}), 3: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date'}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('publish_date', 3)]], {})}, help_text='Add featured article cards (English)', verbose_name='Featured Articles (English)'),
        ),
        migrations.AlterField(
            model_name='practicepage',
            name='featured_articles_ar',
            field=wagtail.fields.StreamField([('card', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Card image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card title', 'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Card description'}), 3: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date'}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('publish_date', 3)]], {})}, help_text='Add featured article cards (English)', null=True, verbose_name='Featured Articles (English)'),
        ),
        migrations.AlterField(
            model_name='practicepage',
            name='featured_articles_en',
            field=wagtail.fields.StreamField([('card', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Card image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card title', 'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Card description'}), 3: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date'}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('publish_date', 3)]], {})}, help_text='Add featured article cards (English)', null=True, verbose_name='Featured Articles (English)'),
        ),
    ]
