# Generated by Django 5.2.10 on 2026-01-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_practicepage_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicepage',
            name='view_count',
        ),
    ]
