# Generated by Django 5.2.10 on 2026-01-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_remove_practicepage_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicepage',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times this page has been viewed', verbose_name='View Count'),
        ),
    ]
